Presentation/App.Admin/Areas/Admin/Controllers/SlideShowController.cs
using App.Core.Caching;
using App.Core.Extensions;
using App.Core.Utilities;
using App.Domain.Slides;
using App.FakeEntity.Slides;
using App.Framework.Utilities;
using App.Service.Languages;
using App.Service.Media;
using App.Service.Settings;
using App.Service.Slides;
using AutoMapper;
using Resources;
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using App.Admin.Helpers;
using App.Core.Logging;

namespace App.Admin.Controllers
{
    public class SlideShowController : BaseAdminController
    {
        private const string CacheSlideshowKey = "db.SlideShow";

	    private readonly ISlideShowService _slideShowService;

        private readonly ILanguageService _languageService;

        private readonly ILocalizedPropertyService _localizedPropertyService;
        private readonly IImageService _imageService;
	    private readonly ISettingService _settingService;

		public SlideShowController(
            ISlideShowService slideShowService
            , ILanguageService languageService
            , ILocalizedPropertyService localizedPropertyService
            , ICacheManager cacheManager, IImageService imageService, ISettingService settingService)
        {
	        _slideShowService = slideShowService;
            _languageService = languageService;
            _localizedPropertyService = localizedPropertyService;
	        _imageService = imageService;
	        _settingService = settingService;

	        //Clear cache
            cacheManager.RemoveByPattern(CacheSlideshowKey);

        }

        public ActionResult Create()
        {
            var model = new SlideShowViewModel
            {
                Status = 1,
                OrderDisplay = 1
            };

            //Add locales to model
            AddLocales(_languageService, model.Locales);

            return View(model);
        }

        [HttpPost]
        public ActionResult Create(SlideShowViewModel model, string returnUrl)
        {
            ActionResult action;
            try
            {
                if (!ModelState.IsValid)
                {
                    var messages = String.Join(Environment.NewLine, ModelState.Values.SelectMany(v => v.Errors)
                                                         .Select(v => v.ErrorMessage + " " + v.Exception));
                    ModelState.AddModelError("", messages);

                    return View(model);
                }

                ImageHandler(model);

                var modelMap = Mapper.Map<SlideShowViewModel, SlideShow>(model);
                _slideShowService.Create(modelMap);

                //Update Localized   
                foreach (var localized in model.Locales)
                {
                    _localizedPropertyService.SaveLocalizedValue(modelMap, x => x.Title, localized.Title, localized.LanguageId);
                    _localizedPropertyService.SaveLocalizedValue(modelMap, x => x.Description, localized.Description, localized.LanguageId);
                }

                Response.Cookies.Add(new HttpCookie("system_message", string.Format(MessageUI.CreateSuccess, FormUI.SlideShow)));
                if (!Url.IsLocalUrl(returnUrl) || returnUrl.Length <= 1 || !returnUrl.StartsWith("/") || returnUrl.StartsWith("//") || returnUrl.StartsWith("/\\"))
                {
                    action = RedirectToAction("Index");
                }
                else
                {
                    action = Redirect(returnUrl);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                LogText.Log(string.Concat("SlideShow.Edit: ", ex.Message));

                return View(model);
            }

            return action;
        }

	    private void ImageHandler(SlideShowViewModel model)
	    {
		    if (model.Image != null && model.Image.ContentLength > 0)
		    {
			    var folderName = CommonHelper.FolderName(model.Title);
			    var fileExtension = Path.GetExtension(model.Image.FileName);
			    var fileNameOriginal = Path.GetFileNameWithoutExtension(model.Image.FileName);

			    var fileName = fileNameOriginal.FileNameFormat(fileExtension);

			    var sizeWidthBg = _settingService.GetSetting("SlideShow.WidthBigSize", ImageSize.WidthDefaultSize);
			    var sizeHeighthBg = _settingService.GetSetting("SlideShow.HeightBigSize", ImageSize.HeightDefaultSize);

				_imageService.CropAndResizeImage(model.Image, $"{Constant.SlideShowFolder}{folderName}/", fileName,sizeWidthBg, sizeHeighthBg);

			    model.ImgPath = $"{Constant.SlideShowFolder}{folderName}/{fileName}";
		    }
	    }

	    public ActionResult Delete(int[] ids)
        {
            try
            {
                if (ids.Length != 0)
                {
                    var numArray = ids;
                    for (var i = 0; i < numArray.Length; i++)
                    {
                        var num = numArray[i];
                        var slideShow = _slideShowService.Get(x => x.Id == num);

                        _slideShowService.Delete(slideShow);

                        //Delete localize
                        var ieLocalizedProperty = _localizedPropertyService.GetByEntityId(num);

                        _localizedPropertyService.BatchDelete(ieLocalizedProperty);
                    }
                }
            }
            catch (Exception ex)
            {
                LogText.Log(string.Concat("SlideShow.Delete: ", ex.Message));
            }

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var modelMap = Mapper.Map<SlideShow, SlideShowViewModel>(_slideShowService.Get(x => x.Id == id));

            //Add Locales to model
            AddLocales(_languageService, modelMap.Locales, (locale, languageId) =>
            {
                locale.Id = modelMap.Id;
                locale.LocalesId = modelMap.Id;
                locale.Title = modelMap.GetLocalized(x => x.Title, modelMap.Id);
                locale.Description = modelMap.GetLocalized(x => x.Description, id);
            });

            return View(modelMap);
        }

        [HttpPost]
        public ActionResult Edit(SlideShowViewModel model, string returnUrl)
        {
            ActionResult action;
            try
            {
                if (!ModelState.IsValid)
                {
                    var messages = String.Join(Environment.NewLine, ModelState.Values.SelectMany(v => v.Errors)
                                                         .Select(v => v.ErrorMessage + " " + v.Exception));
                    ModelState.AddModelError("", messages);

                    return View(model);
                }

                var slideShow = _slideShowService.Get(x => x.Id == model.Id);

	            ImageHandler(model);

				//if (model.Image != null && model.Image.ContentLength > 0)
				//{
				//    var folderName = CommonHelper.FolderName(model.Title);
				//    var fileExtension = Path.GetExtension(model.Image.FileName);
				//    var fileNameOriginal = Path.GetFileNameWithoutExtension(model.Image.FileName);

				//    var fileName = fileNameOriginal.FileNameFormat(fileExtension);

				//    _imageService.CropAndResizeImage(model.Image, $"{Contains.SlideShowFolder}{folderName}/", fileName, ImageSize.SlideShowWithBigSize, ImageSize.SlideShowHeightBigSize);

				//    model.ImgPath = $"{Contains.SlideShowFolder}{folderName}/{fileName}";

				//    //var fileExtension = Path.GetExtension(model.Image.FileName);

				//    //var fileName = model.Title.NonAccent().FileNameFormat(fileExtension);

				//    //var imageServerPath = Path.Combine(Server.MapPath(string.Concat("~/", Contains.AdsFolder)), fileName);

				//    //model.ImgPath = $"{Contains.AdsFolder}/{fileName}";
				//    //model.Image.SaveAs(imageServerPath);
				//}

				var modelMap = Mapper.Map(model, slideShow);
                _slideShowService.Update(modelMap);

                //Update Localized   
                foreach (var localized in model.Locales)
                {
                    _localizedPropertyService.SaveLocalizedValue(modelMap, x => x.Title, localized.Title, localized.LanguageId);
                    _localizedPropertyService.SaveLocalizedValue(modelMap, x => x.Description, localized.Description, localized.LanguageId);
                }

                Response.Cookies.Add(new HttpCookie("system_message", string.Format(MessageUI.UpdateSuccess, FormUI.SlideShow)));
                if (!Url.IsLocalUrl(returnUrl) || returnUrl.Length <= 1 || !returnUrl.StartsWith("/") ||
                    returnUrl.StartsWith("//") || returnUrl.StartsWith("/\\"))
                {
                    action = RedirectToAction("Index");
                }
                else
                {
                    action = Redirect(returnUrl);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                LogText.Log(string.Concat("SlideShow.Edit: ", ex.Message));

                return View(model);
            }

            return action;
        }

        public ActionResult Index(int page = 1, string keywords = "")
        {
            ViewBag.Keywords = keywords;
            var sortingPagingBuilder = new SortingPagingBuilder
            {
                Keywords = keywords,
                Sorts = new SortBuilder
                {
                    ColumnName = "CreatedDate",
                    ColumnOrder = SortBuilder.SortOrder.Descending
                }
            };
            var paging = new Paging
            {
                PageNumber = page,
                PageSize = PageSize,
                TotalRecord = 0
            };

            var slideShows = _slideShowService.PagedList(sortingPagingBuilder, paging);
            if (slideShows != null && slideShows.Any())
            {

Presentation/App.Admin/Areas/Admin/Views/SlideShow/Create.cshtml
@using Resources
@model App.FakeEntity.Slides.SlideShowViewModel
@{
    ViewBag.Title = FormUI.CreateNew;
    ViewBag.Toolbar = new[] { "Save", "SaveNew", "Divider", "Back" };
}
@using (Html.BeginForm("Create", "SlideShow", FormMethod.Post, new { data_container = ViewContext.RouteData.Values["controller"], enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    Html.RenderPartial("_CreateOrUpdate", Model);
}
@section scripts{
    @*<script src="@Url.FakePathAdmin("scripts/plugins/ckeditor/ckeditor.js")"></script>
    <script src="@Url.FakePathAdmin("scripts/plugins/ckeditor/config.js")"></script>*@
    @*<script src="@Url.FakePathAdmin("scripts/plugins/daterangepicker/moment.min.js")"></script>
    <script src="@Url.FakePathAdmin("scripts/plugins/daterangepicker/daterangepicker.js")"></script>
    <script src="@Url.FakePathAdmin("scripts/plugins/daterangepicker/bootstrap-datepicker.js")"></script>
    <script src="@Url.FakePathAdmin("scripts/components-date-time-pickers.js")"></script>*@

}
@section style{
    @*<link href="@Url.FakePathAdmin("content/plugins/daterangepicker/daterangepicker-bs3.css")" rel="stylesheet" />*@

    <script>
        //Copy value từ tên sản phẩm bỏ vào group SEO
        function CopyValue() {
            $("#Locales_0__Title").change(function () {
                var name = $("#Locales_0__Title").val();
                if (name != "") {
                    $("#Locales_0__MetaTitle").val(name);
                    $("#Locales_0__MetaKeywords").val(name);
                    $("#Locales_0__MetaDescription").val(name);

                    $("#Title").val(name);
                    $("#MetaTitle").val(name);
                    $("#MetaKeywords").val(name);
                    $("#MetaDescription").val(name);
                }
            });
        }

        $(function () {
            CopyValue();
        });
    </script>
}

Presentation/App.Admin/Areas/Admin/Views/SlideShow/Edit.cshtml
@using Resources
@model App.FakeEntity.Slides.SlideShowViewModel
@{
    ViewBag.Title = FormUI.Edit;
    ViewBag.Toolbar = new[] { "Save", "SaveNew", "Divider", "Back" };
}
@using (Html.BeginForm("Edit", "SlideShow", FormMethod.Post, new { data_container = ViewContext.RouteData.Values["controller"], enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(x => x.Id)

    Html.RenderPartial("_CreateOrUpdate", Model);

    
}
@section scripts{
    @*<script src="@Url.FakePathAdmin("scripts/plugins/ckeditor/ckeditor.js")"></script>
    <script src="@Url.FakePathAdmin("scripts/plugins/ckeditor/config.js")"></script>*@
    @*<script src="@Url.FakePathAdmin("scripts/plugins/daterangepicker/moment.min.js")"></script>
    <script src="@Url.FakePathAdmin("scripts/plugins/daterangepicker/daterangepicker.js")"></script>
    <script src="@Url.FakePathAdmin("scripts/plugins/daterangepicker/bootstrap-datepicker.js")"></script>
    <script src="@Url.FakePathAdmin("scripts/components-date-time-pickers.js")"></script>*@

<script>
        //Copy value từ tên sản phẩm bỏ vào group SEO
        function CopyValue() {
            $("#Locales_0__Title").change(function () {
                var name = $("#Locales_0__Title").val();
                if (name != "") {
                    $("#Locales_0__MetaTitle").val(name);
                    $("#Locales_0__MetaKeywords").val(name);
                    $("#Locales_0__MetaDescription").val(name);

                    $("#Title").val(name);
                    $("#MetaTitle").val(name);
                    $("#MetaKeywords").val(name);
                    $("#MetaDescription").val(name);
                }
            });
        }

        $(function () {
            CopyValue();
        });
</script>

}
@section style{
    @*<link href="@Url.FakePathAdmin("content/plugins/daterangepicker/daterangepicker-bs3.css")" rel="stylesheet" />*@
}

Presentation/App.Admin/Areas/Admin/Views/SlideShow/Index.cshtml
@using App.Domain.Common
@using App.Framework.Utilities
@using Resources
@model IEnumerable<App.Domain.Slides.SlideShow>
@{
    ViewBag.Title = FormUI.SlideShow;
    ViewBag.Toolbar = new[] {"Create", "Edit", "Delete", "Divider", "Reset"};
}
<table id="@ViewContext.RouteData.Values["controller"]" class="app-grid table table-color table-bordered table-striped table-condensed flip-content table-hover dataTable">
    <thead class="flip-content">
    <tr>
        <th class="text-center"> &nbsp;</th>
        <th class="text-center"> @FormUI.Title </th>
        <th class="text-center"> @FormUI.FromDate </th>
        <th class="text-center"> @FormUI.ToDate </th>
        <th class="text-center"> @FormUI.OrderDisplay </th> 
        <th class="text-center"> @FormUI.Status </th>
        <th class="text-center">
            <input onclick="AppCore.handleCheckAll(this) " type="checkbox">
        </th>
    </tr>
    </thead>
    <tbody>
    @if (Model.Any())
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @if (item.Video)
                    {
                        <video width="120" height="80" controls>
                            <source src="@Url.Content("~/" + item.ImgPath)" type="video/mp4"> 
                        </video>
                    }
                    else
                    {
                        <img alt="@item.Title" src="@item.ImgPath.ValidateImage()" width="80px" />
                    }
                </td>
                <td>
                    <a class="highlight0" href="@Url.Action("Edit", new {id = item.Id, ReturnUrl = Request.Url.PathAndQuery})">@item.Title</a>
                </td>
                <td>@Html.Raw(item.FromDate.HasValue ? String.Format("{0:dd/MM/yyyy HH:mm}", item.FromDate) : string.Empty)</td>
                <td>@Html.Raw(item.ToDate.HasValue ? String.Format("{0:dd/MM/yyyy HH:mm}", item.ToDate) : string.Empty)</td>
                <td>@item.OrderDisplay</td>
                <td>@Html.Raw(item.Status == (int) Status.Disable ? "<span class='label label-sm label-warning'>" + FormUI.InActive + "</span>" : "<span class='label label-sm label-success'>" + FormUI.Active + "</span>")</td>
                <td class="text-center">
                    <input type="checkbox" value="@item.Id">
                </td>
            </tr>
        }
    }
    else
    {
        <tr class="odd">
            <td class="dataTables_empty text-center" colspan="9" valign="top">
                @MessageUI.EmptyItem
            </td>
        </tr>
    }
    </tbody>
</table>
@{ Html.RenderPartial("_PageLinks"); }

Presentation/App.Admin/Areas/Admin/Views/SlideShow/_CreateOrUpdate.cshtml
<!---_CreateOrUpdate--->
@using App.Domain.Common
@using App.Framework.Utilities
@using Resources
@using App.Service.Languages
@model App.FakeEntity.Slides.SlideShowViewModel

<div class="form-horizontal">
    <div class="form-body">
        @Html.ValidationSummary(true, "", new { @class = "text-danger col-md-offset-3" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.Status, new { @class = "control-label col-md-3" })
            <div class="col-md-5">
                <div class="radio-list">
                    <label class="radio-inline">
                        @Html.RadioButtonFor(x => x.Status, (int)Status.Enable, new { @checked = "checked" }) @FormUI.Active
                    </label>
                    <label class="radio-inline">
                        @Html.RadioButtonFor(x => x.Status, (int)Status.Disable) @FormUI.InActive
                    </label>
                </div>
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "help-block" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, new { @class = "control-label col-md-3" })
            <div class="col-md-5">
                <div class="fileinput fileinput-new" data-provides="fileinput">
                    <div class="input-group input-large">
                        <div class="form-control uneditable-input input-fixed input-medium" data-trigger="fileinput">
                            <i class="fa fa-file fileinput-exists"></i>&nbsp;
                            <span class="fileinput-filename"> </span>
                        </div>
                        <span class="input-group-addon btn default btn-file">
                            <span class="fileinput-new">@FormUI.SelectFile</span>
                            <span class="fileinput-exists"> @FormUI.ChangeFile </span>
                            @Html.TextBoxFor(model => model.Image, new { type = "file" })
                        </span>
                        <a href="javascript:;" class="input-group-addon btn red fileinput-exists" data-dismiss="fileinput"> Remove </a>
                    </div>
                </div>
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "help-block" })
            </div>
            <div class="col-md-5 col-md-offset-3">
                @if (!string.IsNullOrEmpty(Model.ImgPath))
                {
                    <img src="@Model.ImgPath.ValidateImage()" width="40px" />
                }
            </div>
        </div>

        <div class="tabbable-line m-heading-1 border-green m-bordered dashboard-stat grey">
            <ul class="nav nav-tabs ">
                @{
                    for (int i = 0; i < Model.Locales.Count; i++)
                    {
                        App.Domain.Languages.Language language = DependencyResolver.Current.GetService<ILanguageService>().GetById(Model.Locales[i].LanguageId);

                        <li class="@(i == 0 ? "active" : "")">
                            <a href="#tab_@(i + 1)" data-toggle="tab"><img src="@language.Flag.ValidateImage()" /> @language.LanguageName</a>
                        </li>
                    }
                }
            </ul>

            <div class="tab-content">
                @{
                    for (int i = 0; i < Model.Locales.Count; i++)
                    {
                        <div class="tab-pane @(i == 0 ? "active" : "")" id="tab_@(i+1)">

                            <div class="form-group">
                                @Html.LabelFor(model => model.Locales[i].Title, new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    @Html.TextBoxFor(model => model.Locales[i].Title, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Locales[i].Title, "", new { @class = "help-block" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Locales[i].Description, new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    @Html.TextAreaFor(model => model.Locales[i].Description, new { @class = "form-control ckeditor" })
                                    @Html.ValidationMessageFor(model => model.Locales[i].Description, "", new { @class = "help-block" })
                                </div>
                            </div>

                        </div>

                        @Html.HiddenFor(model => model.Locales[i].LocalesId)
                        @Html.HiddenFor(model => model.Locales[i].LanguageId)
                    }

                    @Html.HiddenFor(model => model.Title, new { @class = "form-control", Value = Model.Locales[0].Title })
                }

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderDisplay, new { @class = "control-label col-md-3" })
            <div class="col-md-5">
                @Html.TextBoxFor(model => model.OrderDisplay, new { @class = "form-control", type = "number" })
                @Html.ValidationMessageFor(model => model.OrderDisplay, "", new { @class = "help-block" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.WebsiteLink, new { @class = "control-label col-md-3" })
            <div class="col-md-5">
                @Html.TextBoxFor(model => model.WebsiteLink, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.WebsiteLink, "", new { @class = "help-block" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Width, new { @class = "control-label col-md-3" })
            <div class="col-md-5">
                @Html.TextBoxFor(model => model.Width, new { @class = "form-control ckeditor" })
                @Html.ValidationMessageFor(model => model.Width, "", new { @class = "help-block" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Height, new { @class = "control-label col-md-3" })
            <div class="col-md-5">
                @Html.TextBoxFor(model => model.Height, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Height, "", new { @class = "help-block" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Target, new { @class = "control-label col-md-3" })
            <div class="col-md-5">
                <div class="radio-list">
                    <label class="radio-inline">
                        @Html.RadioButtonFor(x => x.Target, TypeLink._blank.ToString(), new { @checked = "checked" }) @TypeLink._blank.ToString()
                    </label>
                    <label class="radio-inline">
                        @Html.RadioButtonFor(x => x.Target, TypeLink._parent.ToString()) @TypeLink._parent.ToString()
                    </label>
                    <label class="radio-inline">
                        @Html.RadioButtonFor(x => x.Target, TypeLink._self.ToString()) @TypeLink._self.ToString()
                    </label>
                    <label class="radio-inline">
                        @Html.RadioButtonFor(x => x.Target, TypeLink._top.ToString()) @TypeLink._top.ToString()
                    </label>
                </div>
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "help-block" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3">@FormUI.DisplayDate</label>
            <div class="col-md-4">
                <div class="input-group input-large date-picker input-daterange" data-date-format="mm/dd/yyyy">
                    @Html.TextBoxFor(model => model.FromDate, "{0:MM/dd/yyyy}", new { @class = "form-control" })
                    <span class="input-group-addon"> to </span>
                    @Html.TextBoxFor(model => model.ToDate, "{0:MM/dd/yyyy}", new { @class = "form-control" })
                </div>
                @Html.ValidationMessageFor(model => model.FromDate, "", new { @class = "help-block" })
                @Html.ValidationMessageFor(model => model.ToDate, "", new { @class = "help-block" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Video, new { @class = "control-label col-md-3" })
            <div class="col-md-5">
                <label class="checkbox">
                    @Html.CheckBoxFor(model => model.Video, new { @class = "" })
                </label>
            </div>
        </div>
    </div>
</div>



<!---/_CreateOrUpdate--->