Presentation/App.Front/Controllers/BannerController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using App.Domain.Common;
using App.Service.Ads;

namespace App.Front.Controllers
{
    public class BannerController : FrontBaseController
    {
        private readonly IBannerService _bannerService;

        public BannerController(IBannerService bannerService)
        {
            _bannerService = bannerService;
        }

        [ChildActionOnly]
        public ActionResult BannerProductHome()
        {
            var banners = _bannerService.GetBanners(status: (int)Status.Enable, position: new List<int> { (int)Position.HomeProduct });

            return PartialView(banners);
        }

        [ChildActionOnly]
        public ActionResult BannerTop(int? menuId, string title)
        {
            var banners = _bannerService.GetBanners(menuId, (int)Status.Enable, new List<int> { (int)Position.Top });
           
            ViewBag.Title = title;

            return PartialView(banners);
        }

        [ChildActionOnly]
        public ActionResult BannerBottom()
        {
            var banners = _bannerService.GetBanners(status: (int)Status.Enable, position: new List<int> { (int)Position.Bottom });

            return PartialView(banners);
        }

        [ChildActionOnly]
        public ActionResult BannerFooter()
        {
            var banners = _bannerService.GetBanners(status: (int)Status.Enable, position: new List<int> { (int)Position.Footer });

            return PartialView(banners);
        }

        [ChildActionOnly]
        public ActionResult BannerLeft()
        {
            var banners = _bannerService.GetBanners(status: (int)Status.Enable, position: new List<int> { (int)Position.Left });

            return PartialView(banners);
        }

        [ChildActionOnly]
        public ActionResult BannerMiddle(int? menuId)
        {
            var banners = _bannerService.GetBanners(status: (int)Status.Enable, position: new List<int> { (int)Position.Middle });

            //var banners = _bannerService.FindBy(x =>
            //    x.MenuId == menuId && x.PageBanner.Position == 6 && x.Status == 1 &&
            //    (!x.FromDate.HasValue ||
            //     DbFunctions.DiffHours(x.ToDate.Value, DateTimeOffset.UtcNow.Offset) >= 0) &&
            //    (!x.ToDate.HasValue ||
            //     DbFunctions.DiffHours(x.ToDate.Value, DateTimeOffset.UtcNow.Offset) <= 0));

            return PartialView(banners);
        }

        [ChildActionOnly]
        public ActionResult BannerOnMenu()
        {
            var banners = _bannerService.GetBanners(status: (int)Status.Enable, position: new List<int> { (int)Position.OnMenu });

            //var banners = _bannerService.FindBy(x =>
            //    x.PageBanner.Position == 8 && x.Status == 1 &&
            //    (!x.FromDate.HasValue ||
            //     DbFunctions.DiffHours(x.ToDate.Value, DateTimeOffset.UtcNow.Offset) >= 0) &&
            //    (!x.ToDate.HasValue ||
            //     DbFunctions.DiffHours(x.ToDate.Value, DateTimeOffset.UtcNow.Offset) <= 0));

            return PartialView(banners);
        }

        [ChildActionOnly]
        public ActionResult BannerRight()
        {
            var banners = _bannerService.GetBanners(status: (int)Status.Enable, position: new List<int> { (int)Position.Right });

            //var banners = _bannerService.FindBy(x =>
            //    x.PageBanner.Position == 4 && x.Status == 1 &&
            //    (!x.FromDate.HasValue ||
            //     DbFunctions.DiffHours(x.ToDate.Value, DateTimeOffset.UtcNow.Offset) >= 0) &&
            //    (!x.ToDate.HasValue ||
            //     DbFunctions.DiffHours(x.ToDate.Value, DateTimeOffset.UtcNow.Offset) <= 0));

            return PartialView(banners);
        }

        [ChildActionOnly]
        public ActionResult BannerSideBar(int? menuId)
        {
            var banners = _bannerService.GetBanners(status: (int)Status.Enable, position: new List<int> { (int)Position.SiderBar });

            return PartialView(banners);
        }
    }
}

Presentation/App.Front/Controllers/NewsController.cs
using App.Core.Extensions;
using App.Core.Utilities;
using App.Domain.Common;
using App.Domain.Menus;
using App.Domain.News;
using App.Framework.Utilities;
using App.Front.Extensions;
using App.Front.Models;
using App.Service.Languages;
using App.Service.Menus;
using App.Service.News;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace App.Front.Controllers
{
    public class NewsController : FrontBaseController
    {
        private readonly INewsService _newsService;

        private readonly IMenuLinkService _menuLinkService;

        public NewsController(
            INewsService newsService
            , IMenuLinkService menuLinkService)
        {
            _newsService = newsService;
            _menuLinkService = menuLinkService;
        }

        [ChildActionOnly]
        [PartialCache("Long", "*")]
        public ActionResult BreadCrumNews(string virtualId)
        {
            var menuLinks = new List<MenuLink>();

            var exsitingMenu = _menuLinkService.FindBy(x => x.TemplateType == (int)TemplateContent.News && x.Status == (int)Status.Enable, true);
            if (!exsitingMenu.IsAny())
            {
                return PartialView(menuLinks);
            }

            menuLinks.AddRange(exsitingMenu);

            ViewBag.TitleNews = exsitingMenu.ElementAt(0).MenuName;
            ViewBag.VirtualId = virtualId;

            return PartialView(menuLinks);
        }

        [ChildActionOnly]
        [PartialCache("Long")]
        public ActionResult NewsHome()
        {
            var existingPosts = _newsService.GetByOption(isDisplayHomePage: true);
            if (!existingPosts.IsAny())
            {
                return null;
            }

            var posts = existingPosts.Select(x => x.ToModel());

            existingPosts = from x in posts orderby x.OrderDisplay descending select x;

            return PartialView(existingPosts);
        }

        [PartialCache("Long", "*")]
        public ActionResult NewsCategories(string virtualCategoryId, int? menuId, string title, int page, int? month, int? year)
        {
            var sortBuilder = new SortBuilder
            {
                ColumnName = "CreatedDate",
                ColumnOrder = SortBuilder.SortOrder.Descending
            };
            var paging = new Paging
            {
                PageNumber = page,
                PageSize = CommonHelper.PageSize,
                TotalRecord = 0
            };

            var news = _newsService.FindAndSort(x => !x.Video && x.Status == (int)Status.Enable && x.VirtualCategoryId.Contains(virtualCategoryId)
            , sortBuilder, paging);

            if (news == null)
            {
                return HttpNotFound();
            }

            //Expression<Func<StaticContent, bool>> status = x => x.Status == (int)Status.Enable;
            //ViewBag.fixItems = _staticContentService.GetTop(3, status, x => x.ViewCount);

            if (month != null)
            {
                news = news.Where(n => n.CreatedDate.Month == month);
            }

            if (year != null)
            {
                news = news.Where(n => n.CreatedDate.Year == year);
            }

            var newsLocalized = news.Select(x => x.ToModel());

            if (news.IsAny())
            {
                var menuCategoryFilter = _menuLinkService.GetByOptions(virtualId: virtualCategoryId);
                if (menuCategoryFilter.IsAny())
                {
                    ViewBag.BannerId = menuCategoryFilter.FirstOrDefault(x => x.VirtualId == virtualCategoryId).Id;
                }

                var pageInfo = new Helper.PageInfo(CommonHelper.PageSize, page, paging.TotalRecord,
                    i => Url.Action("GetContent", "Menu", new { page = i }));
                ViewBag.PageInfo = pageInfo;
                ViewBag.CountItem = pageInfo.TotalItems;

                var breadCrumbs = new List<BreadCrumb>();
                var categoryIds = virtualCategoryId.Split('/');
                for (var i = 0; i < categoryIds.Length; i++)
                {
                    var categoryId = categoryIds[i];
                    var menuLink = _menuLinkService.GetByMenuName(categoryId, title);
                    if (menuLink != null)
                    {
                        if (i == 0)
                        {
                            ViewBag.BannerId = menuLink.Id;
                        }

                        breadCrumbs.Add(new BreadCrumb
                        {
                            Title = menuLink.GetLocalized(m => m.MenuName, menuLink.Id),
                            Current = false,
                            Url = Url.Action("GetContent", "Menu", new { area = "", menu = menuLink.SeoUrl })
                        });
                    }
                }

                breadCrumbs.Add(new BreadCrumb
                {
                    Current = true,
                    Title = title
                });

                ViewBag.BreadCrumb = breadCrumbs;
            }

            ViewBag.MenuId = menuId;
            ViewBag.VirtualId = virtualCategoryId;
            ViewBag.Title = title;

            return PartialView(newsLocalized);
        }

        [ChildActionOnly]
        [PartialCache("Long", "*")]
        public ActionResult NewsRelative(string virtualId, int newsId)
        {
            var news = new List<News>();
            var newses = _newsService.GetTop(4,
                x => x.Status == (int)Status.Enable && x.VirtualCategoryId.Contains(virtualId) && x.Id != newsId &&
                     !x.Video, x => x.ViewCount);
            if (newses.IsAny())
            {
                news.AddRange(newses);
            }

            return PartialView(news);
        }

        [PartialCache("Long")]
        [ChildActionOnly]
        public ActionResult GetVideoSlide()
        {
            var news = new List<News>();
            var newses = _newsService.FindBy(x => x.Video && x.Status == (int)Status.Enable, true);
            if (newses.IsAny())
            {
                news.AddRange(newses);
            }

            return PartialView(news);
        }

        [PartialCache("Long", "*")]
        public ActionResult NewsDetail(string seoUrl)
        {
            var breadCrumbs = new List<BreadCrumb>();
            var news = _newsService.Get(x => x.SeoUrl.Equals(seoUrl), true);

            if (news == null)
            {
                return HttpNotFound();
            }

            News newsLocalized;
            {
                newsLocalized = news.ToModel();

                ViewBag.Title = newsLocalized.MetaTitle;
                ViewBag.KeyWords = newsLocalized.MetaKeywords;
                ViewBag.SiteUrl = Url.Action("NewsDetail", "News", new { seoUrl, area = "" });
                ViewBag.Description = newsLocalized.MetaDescription;
                ViewBag.Image = Url.Content(string.Concat("~/", newsLocalized.ImageBigSize));
                ViewBag.MenuId = newsLocalized.MenuId;
                ViewBag.VirtualId = newsLocalized.VirtualCategoryId;

                var categories = newsLocalized.VirtualCategoryId.Split('/');
                for (var i = 0; i < categories.Length; i++)
                {
                    var category = categories[i];
                    var menuLink = _menuLinkService.Get(x => x.CurrentVirtualId.Equals(category));

                    if (i == 0)
                    {
                        ViewBag.BannerId = menuLink.Id;
                    }

                    breadCrumbs.Add(new BreadCrumb
                    {
                        Title = menuLink.GetLocalized(m => m.MenuName, menuLink.Id),
                        Current = false,
                        Url = Url.Action("GetContent", "Menu", new { area = "", menu = menuLink.SeoUrl })
                    });
                }
                breadCrumbs.Add(new BreadCrumb
                {
                    Current = true,
                    Title = newsLocalized.Title
                });
                ViewBag.BreadCrumb = breadCrumbs;
            }

            ViewBag.SeoUrl = newsLocalized.MenuLink.SeoUrl;

            return View(newsLocalized);
        }

        /// <summary>
        /// Lấy tất cả bài viết nhóm theo tháng, năm.
        /// </summary>
        /// <returns></returns>       
        [PartialCache("Long", "*")]
        public ActionResult NewsTimeLine()
        {
            var news = _newsService.GetAll();

            if (news == null)
            {
                return HttpNotFound();
            }

            var newsGroup = news.GroupBy(l => l.CreatedDate.Year + 12 + l.CreatedDate.Month)
                .Select(g => g.First().ToModel()).ToList();

            ViewBag.NewsGroup = newsGroup;

            return PartialView(newsGroup);
        }
    }
}

Presentation/App.Front/Views/News/BreadCrumNews.cshtml
<!---BreadCrumNews-->
@using App.Core.Extensions
@model List<App.Domain.Menus.MenuLink>
@if (Model.IsAny())
{
    <div id="vnt-navation" class="breadcrumb">
        <div class="wrapper">
            <div class="navation">
                <ul class="list-inline text-left">
                    @foreach (var item in Model)
                    {
                        if (item.CurrentVirtualId.Equals(ViewBag.VirtualId))
                        {
                            <li class="active"><a href="@Url.Action("GetContent", "Menu", new {menu = item.SeoUrl, area = ""})">@item.MenuName</a></li>
                        }
                        else
                        {
                            <li class="active"><a href="@Url.Action("GetContent", "Menu", new {menu = item.SeoUrl, area = ""})">@item.MenuName</a></li>
                        }

                    }                    
                </ul>
            </div>
        </div>
    </div>
}
<!---/BreadCrumNews-->

Presentation/App.Front/Views/News/NewsCategories.cshtml
<!--NewsCategories---->
@using App.Core.Extensions
@using App.Framework.Utilities
@model IEnumerable<App.Domain.News.News>
@if (Model.IsAny())
{
    Html.RenderAction("BannerTop", "Banner", new { menuId = ViewBag.BannerId, title = ViewBag.Title });

    <div class="columns-container">
        <div class="container" id="columns">
            @Html.Partial("_BreadCrumb")

            <!-- row -->
            <div class="row">
                <!-- Left colunm -->
                <div class="column col-xs-12 col-sm-3" id="left_column">
                    @{Html.RenderAction("MenuNavNews", "MenuNav", new { virtualId = ViewBag.VirtualId, area = "" });}

                </div>
                <!-- ./left colunm -->
                <!-- Center colunm-->
                <div class="center_column col-xs-12 col-sm-9" id="center_column">
                    <h2 class="page-heading">
                        <span class="page-heading-title2">@ViewBag.Title</span>
                    </h2>

                    <ul class="blog-posts">
                        @foreach (var item in Model)
                        {
                            <li class="post-item">
                                <article class="entry">
                                    <div class="row">
                                        <div class="col-sm-5">
                                            <div class="entry-thumb image-hover2">
                                                <a href="@Url.Action("NewsDetail", "News", new {seoUrl = item.SeoUrl, area = ""})" title="@item.Title">
                                                    <img src="@item.ImageMediumSize.ValidateImage()" alt="@item.Title">
                                                </a>
                                            </div>
                                        </div>
                                        <div class="col-sm-7">
                                            <div class="entry-ci">
                                                <h3 class="entry-title">
                                                    <a href="@Url.Action("NewsDetail", "News", new {seoUrl = item.SeoUrl, area = ""})" title="@item.Title">
                                                        @item.Title
                                                    </a>
                                                </h3>
                                                <div class="entry-meta-data">

                                                    <span class="date"><i class="fa fa-calendar"></i>  @item.CreatedDate.ToString("dd/MM/yyyy")</span>
                                                </div>

                                                <div class="entry-excerpt">
                                                    @Html.Raw(item.ShortDesc)
                                                </div>
                                                <div class="entry-more">
                                                    <a href="@Url.Action("NewsDetail", "News", new {seoUrl = item.SeoUrl, area = ""})" title="@item.Title">@T("XemChiTiet")</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </article>
                            </li>
                        }


                    </ul>
                    @{Html.RenderPartial("_PagedLinks");}
                </div>
                <!-- ./ Center colunm -->
            </div>
            <!-- ./row-->
        </div>
    </div>

}
<!--/NewsCategories---->

Presentation/App.Front/Views/News/NewsDetail.cshtml
<!--NewsDetail---->
@using App.Framework.Utilities
@model App.Domain.News.News

@if (Model != null)
{
	Html.RenderAction("BannerTop", "Banner", new { menuId = ViewBag.BannerId, title = ViewBag.Title });
	<div class="columns-container">
		<div class="container" id="columns">
			@Html.Partial("_BreadCrumb")
			<!-- row -->
			<div class="row">
				<!-- Left colunm -->
				<div class="column col-xs-12 col-sm-3" id="left_column">
					@{
						Html.RenderAction("MenuNavNews", "MenuNav", new { virtualId = ViewBag.VirtualId, area = "" });
						Html.RenderAction("NewsTimeLine", "News", new { area = "" });
						Html.RenderAction("PostHot", "Post", new { area = "" });
					}

				</div>
				<!-- ./left colunm -->
				<!-- Center colunm-->
				<div class="center_column col-xs-12 col-sm-9" id="center_column">
					<h1 class="page-heading">
						<span class="page-heading-title2">@Model.Title</span>
					</h1>
					<article class="entry-detail">
						<div class="entry-meta-data">
							<span class="author">
								<i class="fa fa-user"></i>
								by: <a href="#">@Model.CreatedBy</a>
							</span>

							<span class="date"><i class="fa fa-calendar"></i> @Model.CreatedDate.ToString("dd/MM/yyyy")</span>

						</div>
						<div class="entry-photo">
							<img src="@Model.ImageBigSize.ValidateImage()" alt="@Model.Title" title="@Model.Title">
						</div>
						<div class="content-text clearfix">
							@Html.Raw(Model.Description)
						</div>

					</article>
					@{

						Html.RenderAction("NewsRelative", "News", new { virtualId = Model.MenuLink.VirtualId, newsId = Model.Id, area = "" });
					}

				</div>
				<!-- ./ Center colunm -->
			</div>
			<!-- ./row-->
		</div>
	</div>
}

<!--/NewsDetail---->

Presentation/App.Front/Views/News/NewsHome.cshtml
<!---NewsHome--->
@using App.Core.Extensions
@using App.Framework.Utilities
@model IEnumerable<App.Domain.News.News>

@if (Model.IsAny())
{
    <section id="cus-talk">
        <div class="wrap-datb-home">
            <h2 class="title_home">Cảm nhận khách hàng</h2>
            <div class="wrap-list-customer row">
                <div id="owl-khabout" class="owl-carousel owl-theme">
                    @foreach (var item in Model)
                    {
                        <div class="item">
                            <div class=" cus-item">
                                <div class="ideal-cus">
                                    <div class="carret-bot">
                                        <img src="http://www.datsolar.com/templates/skins/images/ar-down.png">
                                    </div>
                                    <div>
                                        @Html.Raw(item.ShortDesc)
                                    </div>
                                </div>
                                <div class="col-sm-12 cus-info">
                                    `
                                    <div class="img-cus">
                                        <img src="@item.ImageMediumSize.ValidateImage()" alt='@item.Title'>
                                    </div>
                                    <div class="info-cus">
                                        <a href="@Url.Action("NewsDetail", "News", new {seoUrl = item.SeoUrl, area = ""})" title="@item.Title">
                                            @*<p class="name-cus">Anh Nguyễn Đăng Tuấn</p>*@
                                        </a>
                                        <p class="place-cus">@item.Title</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>
}

<!---/NewsHome--->

Presentation/App.Front/Views/News/NewsRelative.cshtml
@using App.Core.Extensions
@using App.Framework.Utilities
@model IEnumerable<App.Domain.News.News>
@if (Model.IsAny())
{
    <div class="single-box">
        <h2>Tin liên quan</h2>
        <ul class="gw-news-relative related-posts owl-carousel">
            @foreach (var item in Model)
            {
                <li class="post-item">
                    <article class="entry">
                        <div class="entry-thumb image-hover2">
                            <a href="@Url.Action("NewsDetail", "News", new {seoUrl = item.SeoUrl, area = ""})">
                                <img src="@item.ImageMediumSize.ValidateImage()" alt="@item.Title" />
                            </a>
                        </div>
                        <div class="entry-ci">
                            <h3 class="entry-title">
                                <a href="@Url.Action("NewsDetail", "News", new {seoUrl = item.SeoUrl, area = ""})">
                                    @item.Title
                                </a>
                            </h3>
                            <div class="entry-meta-data">
                                <span class="date">
                                    <i class="fa fa-calendar"></i> @item.CreatedDate.ToString("dd/MM/yyyy")
                                </span>
                            </div>

                        </div>
                    </article>
                </li>
            }
           
        </ul>
    </div>
}

Presentation/App.Front/Views/News/NewsTimeLine.cshtml
<!----NewsTimeLine-->
@using App.Core.Extensions
@model IEnumerable<App.Domain.News.News>

@if (Model.IsAny())
{
    <div class="block left-module">
        <p class="title_block">@T("DanhMuc")</p>
        <div class="block_content">
            <!-- layered -->
            <div class="layered layered-category">
                <div class="layered-content">
                    <ul class="tree-menu">
                        @foreach (var item in Model)
                        {
                            <li>
                                <span></span>
                                <a href="@Url.Action("GetContent", "Menu", new {menu = "tin-tuc", month = item.CreatedDate.Month, year = item.CreatedDate.Year, area = ""})">
                                    @string.Format("Tháng {0} - năm {1}", item.CreatedDate.Month, item.CreatedDate.Year)
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
            <!-- ./layered -->
        </div>
    </div>



}

<!----/NewsTimeLine-->