Presentation/App.Front/Models/ContactForm.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace App.Front.Models
{
	public class ContactForm
	{
	    [DisplayName("Nội dung liên hệ")]
        public string Content
		{
			get;
			set;
		}

	    [Required(ErrorMessage = "Vui lòng nhập email.")]
        public string Email
		{
			get;
			set;
		}

        [DisplayName("Tên của bạn")]
        [Required(ErrorMessage = "Vui lòng nhập tên.")]
        public string FullName
		{
			get;
			set;
		}

	    public bool SuccessfullySent { get; set; }
	    public string Result { get; set; }
    }
}

Presentation/App.Front/Controllers/ContactController.cs
using App.Domain.Common;
using App.Domain.ServerMails;
using App.Front.Extensions;
using App.Front.Models;
using App.Service.ContactInformations;
using App.Service.MailSetting;
using App.Service.Menus;
using App.Service.Messages;
using App.Service.SystemApp;
using System;
using System.Linq;
using System.Web.Mvc;
using System.Xml;
using App.Framework.Utilities;

namespace App.Front.Controllers
{
    public class ContactController : FrontBaseController
    {
        private readonly IContactInformationService _contactInfoService;
        private readonly ISystemSettingService _systemSettingService;
        private readonly ISendMailService _sendMailService;

        public ContactController(IContactInformationService contactInfoService, IMenuLinkService menuLinkService
            , IMailSettingService mailSettingService
            , ISystemSettingService systemSettingService
            , ISendMailService sendMailService)
        {
            _contactInfoService = contactInfoService;
            _systemSettingService = systemSettingService;
            _sendMailService = sendMailService;
        }

        [PartialCache("Long")]
        public ActionResult ContactUs()
        {
            var contactInformation = _contactInfoService.FindBy(x => x.Status == (int)Status.Enable, true);

            if (contactInformation == null)
            {
                return HttpNotFound();
            }

            var contactInformationLocalize = contactInformation.Select(x => x.ToModel());
            
            //ViewBag.Title = title;
            ViewBag.Contact = contactInformationLocalize;

            var contact = new ContactForm();

            return PartialView(contact);
        }
        
        public ActionResult SendContact(ContactForm model)
        {
            try
            {
                if (!Request.IsAjaxRequest())
                {
                    return Json(new
                    {
                        title="Gửi liên hệ",
                        success = false,
                        errors = string.Join(", ", ModelState.Values.SelectMany(v =>
                            from x in v.Errors
                            select x.ErrorMessage).ToArray())
                    });
                }

                var serverPathEmail = string.Concat(Server.MapPath("\\"), Constant.TemplateMailBasicContact);
                if (System.IO.File.Exists(serverPathEmail))
                {
                    const string messageId = "Email";
                    var subject = "Thông tin liên hệ";

                    var body = string.Concat("", "Người gửi: ", model.FullName, "<br>");
                    body = string.Concat(body, string.Concat("E-mail: ", model.Email), "<br>");
                    body = string.Concat(body, model.Content, "<br>");

                    var xmlDocument = new XmlDocument();
                    xmlDocument.Load(serverPathEmail);
                    var xmlNodes = xmlDocument.SelectSingleNode(string.Concat("MailFormats/MailFormat[@Id='", messageId, "']"));

                    var subjectNodes = xmlNodes.SelectSingleNode("Subject")?.InnerText;
                    subjectNodes = subject.Replace(string.Concat(subject, "?"), subject);

                    var bodyNodes = xmlNodes.SelectSingleNode("Body")?.InnerText;
                    bodyNodes = body.Replace(string.Concat(body, "?"), body);

                    var toEmail = _systemSettingService.Get(x => x.Status == 1).Email;

                    var sendMail = new SendMail
                    {
                        MessageId = "Email",
                        ToEmail = toEmail,
                        Subject = subjectNodes,
                        Body = bodyNodes
                    };

                     _sendMailService.SendMailSmtp(sendMail);

                    model.SuccessfullySent = true;
                    model.Result = "Gửi liên hệ thành công, chúng tôi sẽ liên lạc với bạn ngay khi có thể.";
                }

                return Json(new
                {
                    title = "Gửi liên hệ",
                    success = true,
                    message = "Gửi liên hệ không thành công. Vui lòng liên hệ người quản lý."
                });

            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
    }
}

Presentation/App.Front/Views/Contact/ContactUs.cshtml
<!----ContactUS--->
@using App.Domain.ContactInformations
@using App.Framework.UI.Extensions
@model App.Front.Models.ContactForm

@{
    <div class="columns-container" id="contact">
        <div class="gw-contact-shop container " id="columns">
            <div class="breadcrumb clearfix">
                <a class="home" href="#" title="Return to Home">Home</a>
                <span class="navigation-pipe">&nbsp;</span>
                <span class="navigation_page">Contact</span>
            </div>
            <div class="row clearfix">
                <div class="col-md-12 col-xs-12" id="layout-page">

                    <span class="header-contact header-page clearfix">
                        <h1>Liên hệ</h1>
                    </span>

                    <div class="content-contact content-page clearfix">

                        <p class="text-center">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.310729061172!2d106.6539626784669!3d10.787496261978522!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752ecbb6275cc3%3A0x634b1cfb9f2ed0be!2zNTYgVsOibiBDw7RpLCBwaMaw4budbmcgNywgVMOibiBCw6xuaCwgSOG7kyBDaMOtIE1pbmgsIFZpZXRuYW0!5e0!3m2!1sen!2s!4v1446015505979" width="100%" height="500" frameborder="0" style="border: 0" allowfullscreen=""></iframe>
                        </p>

                        <div class="col-md-7" id="col-left contactFormWrapper">
                            <h3 class="page-subheading">Viết nhận xét</h3>
                            <hr class="line-left">
                            <p>
                                Nếu bạn có thắc mắc gì, có thể gửi yêu cầu cho chúng tôi, và chúng tôi sẽ liên lạc lại với bạn sớm nhất có thể .
                            </p>
                            @using (Html.BeginForm("SendContact", "Contact", FormMethod.Post, new { enctype = "multipart/form-data", id = "form-send-Contact", @class = "form-horizontal" }))
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-group">
                                    @Html.TextBoxFor(model => model.FullName, new { @class = "form-control input-lg", required = true, autocapitalize = "words", placeholder = Html.DisplayPlaceHolderFor(m => m.FullName) })
                                    @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "has-error" })
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(mode => Model.FullName, new { @class = "sr-only" })
                                    @Html.TextBoxFor(model => model.FullName, new { @class = "form-control input-lg", required = true, autocapitalize = "words", placeholder = Html.DisplayPlaceHolderFor(m => m.FullName) })
                                    @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "has-error" })
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(mode => Model.Email, new { @class = "sr-only" })
                                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control input-lg", required = true, autocapitalize = "words", placeholder = Html.DisplayPlaceHolderFor(m => m.Email) })
                                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "has-error" })
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(mode => Model.Content, new { @class = "sr-only" })
                                    @Html.TextAreaFor(model => model.Content, new { rows = "6", @class = "form-control input-lg", required = true, autocapitalize = "words", placeholder = Html.DisplayPlaceHolderFor(m => m.Content) })
                                </div>

                                <button id="btn-send-contact" type="submit" class="btn">
                                    <i class="glyphicon glyphicon-envelope"></i>
                                    Gửi thông tin
                                </button>
                            }
                        </div>

                        <div class="col-md-5" id="col-right">
                            @{Html.RenderPartial("_ContactPartial", (IEnumerable<ContactInformation>)ViewBag.Contact);}
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
}



<!----/ContactUS--->